export const APP_GET_SELECTED_USER = 'app/selectedUser/APP_GET_SELECTED_USER';
export const GET_SELECTED_USER_REQUEST = 'app/selectedUser/GET_SELECTED_USER_REQUEST';
export const GET_SELECTED_USER_ERROR = 'app/selectedUser/GET_SELECTED_USER_ERROR';
export const GET_SELECTED_USER_SUCCESS = 'app/selectedUser/GET_SELECTED_USER_SUCCESS'


export const APP_GET_SELECTED_USER_POST_LIST = 'app/selectedUser/APP_GET_SELECTED_USER_POST_LIST';
export const GET_SELECTED_USER_POST_LIST_REQUEST = 'app/selectedUser/GET_SELECTED_USER_POST_LIST_REQUEST'
export const GET_SELECTED_USER_POST_LIST_ERROR = 'app/selectedUser/GET_SELECTED_USER_POST_LIST_ERROR'
export const GET_SELECTED_USER_POST_LIST_SUCCESS = 'app/selectedUser/GET_SELECTED_USER_POST_LIST_SUCCESS'


export const APP_GET_SELECTED_USER_POST = 'app/selectedUser/APP_GET_SELECTED_USER_POST';
export const GET_SELECTED_USER_POST_REQUEST = 'app/selectedUser/GET_SELECTED_USER_POST_REQUEST'
export const GET_SELECTED_USER_POST_ERROR = 'app/selectedUser/GET_SELECTED_USER_POST_ERROR'
export const GET_SELECTED_USER_POST_SUCCESS = 'app/selectedUser/GET_SELECTED_USER_POST_SUCCESS'